import { createSlice } from '@reduxjs/toolkit'

const initialCounterState = {
    counter: 0,
    showCounter: true
}

const counterSlice = createSlice({
    name: 'counter',
    initialState: initialCounterState,
    reducers: {
        increment(state) {
            console.log(state.counter)
            state.counter++
         },
        increase(state, action) {
            state.counter = state.counter + action.payload
         },
        decrement(state) {
            state.counter--
         },
        toggle(state) {
            state.showCounter = !state.showCounter
         }
    }
})

export const counterActions = counterSlice.actions //contain all the action creators automatically generated by Redux Toolkit for the counterSlice

export default counterSlice.reducer