
import { createSlice, configureStore, combineReducers } from '@reduxjs/toolkit'

const initialCounterState = {
    counter: 0,
    showCounter: true
}

const counterSlice = createSlice({
    name: 'counter',
    initialState: initialCounterState,
    reducers: {
        increment(state) {
            console.log(state.counter)
            state.counter++
         },
        increase(state, action) {
            state.counter = state.counter + action.payload
         },
        decrement(state) {
            state.counter--
         },
        toggle(state) {
            state.showCounter = !state.showCounter
         }
    }
})

const initialAuthState = { isAuthenticated: false}

const authSlice = createSlice({
    name: "auth",
    initialState: initialAuthState,
    reducers: {
        login(state) {
            state.isAuthenticated = true
        },
        logout(state) {
            state.isAuthenticated = false
        }
    }
})


const store = configureStore({
    reducer: combineReducers({
        counter: counterSlice.reducer, //counter will be used for the selector
        auth: authSlice.reducer // auth will be used for the selector, state.auth.isAuthenticated
    })
})

export const counterActions = counterSlice.actions //contain all the action creators automatically generated by Redux Toolkit for the counterSlice
export const {login, logout} = authSlice.actions

export default store //connect react application to the store